class zoomcodes:
  def CountryCodes(country): #@NoSelf
    countrycodes={
    "Andorra":"AD",
    "United Arab Emirates":"AE",
    "Afghanistan":"AF",
    "Antigua and Barbuda":"AG",
    "Anguilla":"AI",
    "Albania":"AL",
    "Armenia":"AM",
    "Angola":"AO",
    "Asia/Pacific Region":"AP",
    "Antarctica":"AQ",
    "Argentina":"AR",
    "American Samoa":"AS",
    "Austria":"AT",
    "Australia":"AU",
    "Aruba":"AW",
    "Aland Islands":"AX",
    "Azerbaijan":"AZ",
    "Bosnia and Herzegovina":"BA",
    "Barbados":"BB",
    "Bangladesh":"BD",
    "Belgium":"BE",
    "Burkina Faso":"BF",
    "Bulgaria":"BG",
    "Bahrain":"BH",
    "Burundi":"BI",
    "Benin":"BJ",
    "Saint Barthelemy":"BL",
    "Bermuda":"BM",
    "Brunei Darussalam":"BN",
    "Bolivia":"BO",
    "Bonaire, Saint Eustatius and Saba":"BQ",
    "Brazil":"BR",
    "Bahamas":"BS",
    "Bhutan":"BT",
    "Bouvet Island":"BV",
    "Botswana":"BW",
    "Belarus":"BY",
    "Belize":"BZ",
    "Canada":"CA",
    "Cocos (Keeling) Islands":"CC",
    "Congo, The Democratic Republic of the":"CD",
    "Central African Republic":"CF",
    "Congo":"CG",
    "Switzerland":"CH",
    "Cote d'Ivoire":"CI",
    "Cook Islands":"CK",
    "Chile":"CL",
    "Cameroon":"CM",
    "China":"CN",
    "Colombia":"CO",
    "Costa Rica":"CR",
    "Cuba":"CU",
    "Cape Verde":"CV",
    "Curacao":"CW",
    "Christmas Island":"CX",
    "Cyprus":"CY",
    "Czech Republic":"CZ",
    "Germany":"DE",
    "Djibouti":"DJ",
    "Denmark":"DK",
    "Dominica":"DM",
    "Dominican Republic":"DO",
    "Algeria":"DZ",
    "Ecuador":"EC",
    "Estonia":"EE",
    "Egypt":"EG",
    "Western Sahara":"EH",
    "Eritrea":"ER",
    "Spain":"ES",
    "Ethiopia":"ET",
    "Europe":"EU",
    "Finland":"FI",
    "Fiji":"FJ",
    "Falkland Islands (Malvinas)":"FK",
    "Micronesia, Federated States of":"FM",
    "Faroe Islands":"FO",
    "France":"FR",
    "Gabon":"GA",
    "United Kingdom":"GB",
    "Grenada":"GD",
    "Georgia":"GE",
    "French Guiana":"GF",
    "Guernsey":"GG",
    "Ghana":"GH",
    "Gibraltar":"GI",
    "Greenland":"GL",
    "Gambia":"GM",
    "Guinea":"GN",
    "Guadeloupe":"GP",
    "Equatorial Guinea":"GQ",
    "Greece":"GR",
    "South Georgia and the South Sandwich Islands":"GS",
    "Guatemala":"GT",
    "Guam":"GU",
    "Guinea-Bissau":"GW",
    "Guyana":"GY",
    "Hong Kong":"HK",
    "Heard Island and McDonald Islands":"HM",
    "Honduras":"HN",
    "Croatia":"HR",
    "Haiti":"HT",
    "Hungary":"HU",
    "Indonesia":"ID",
    "Ireland":"IE",
    "Israel":"IL",
    "Isle of Man":"IM",
    "India":"IN",
    "British Indian Ocean Territory":"IO",
    "Iraq":"IQ",
    "Iran, Islamic Republic of":"IR",
    "Iceland":"IS",
    "Italy":"IT",
    "Jersey":"JE",
    "Jamaica":"JM",
    "Jordan":"JO",
    "Japan":"JP",
    "Kenya":"KE",
    "Kyrgyzstan":"KG",
    "Cambodia":"KH",
    "Kiribati":"KI",
    "Comoros":"KM",
    "Saint Kitts and Nevis":"KN",
    "Korea, Democratic People's Republic of":"KP",
    "Korea, Republic of":"KR",
    "Kuwait":"KW",
    "Cayman Islands":"KY",
    "Kazakhstan":"KZ",
    "Lao People's Democratic Republic":"LA",
    "Lebanon":"LB",
    "Saint Lucia":"LC",
    "Liechtenstein":"LI",
    "Sri Lanka":"LK",
    "Liberia":"LR",
    "Lesotho":"LS",
    "Lithuania":"LT",
    "Luxembourg":"LU",
    "Latvia":"LV",
    "Libyan Arab Jamahiriya":"LY",
    "Morocco":"MA",
    "Monaco":"MC",
    "Moldova, Republic of":"MD",
    "Montenegro":"ME",
    "Saint Martin":"MF",
    "Madagascar":"MG",
    "Marshall Islands":"MH",
    "Macedonia":"MK",
    "Mali":"ML",
    "Myanmar":"MM",
    "Mongolia":"MN",
    "Macao":"MO",
    "Northern Mariana Islands":"MP",
    "Martinique":"MQ",
    "Mauritania":"MR",
    "Montserrat":"MS",
    "Malta":"MT",
    "Mauritius":"MU",
    "Maldives":"MV",
    "Malawi":"MW",
    "Mexico":"MX",
    "Malaysia":"MY",
    "Mozambique":"MZ",
    "Namibia":"NA",
    "New Caledonia":"NC",
    "Niger":"NE",
    "Norfolk Island":"NF",
    "Nigeria":"NG",
    "Nicaragua":"NI",
    "Netherlands":"NL",
    "Norway":"NO",
    "Nepal":"NP",
    "Nauru":"NR",
    "Niue":"NU",
    "New Zealand":"NZ",
    "Oman":"OM",
    "Panama":"PA",
    "Peru":"PE",
    "French Polynesia":"PF",
    "Papua New Guinea":"PG",
    "Philippines":"PH",
    "Pakistan":"PK",
    "Poland":"PL",
    "Saint Pierre and Miquelon":"PM",
    "Pitcairn":"PN",
    "Puerto Rico":"PR",
    "Palestinian Territory":"PS",
    "Portugal":"PT",
    "Palau":"PW",
    "Paraguay":"PY",
    "Qatar":"QA",
    "Reunion":"RE",
    "Romania":"RO",
    "Serbia":"RS",
    "Russian Federation":"RU",
    "Rwanda":"RW",
    "Saudi Arabia":"SA",
    "Solomon Islands":"SB",
    "Seychelles":"SC",
    "Sudan":"SD",
    "Sweden":"SE",
    "Singapore":"SG",
    "Saint Helena":"SH",
    "Slovenia":"SI",
    "Svalbard and Jan Mayen":"SJ",
    "Slovakia":"SK",
    "Sierra Leone":"SL",
    "San Marino":"SM",
    "Senegal":"SN",
    "Somalia":"SO",
    "Suriname":"SR",
    "South Sudan":"SS",
    "Sao Tome and Principe":"ST",
    "El Salvador":"SV",
    "Sint Maarten":"SX",
    "Syrian Arab Republic":"SY",
    "Swaziland":"SZ",
    "Turks and Caicos Islands":"TC",
    "Chad":"TD",
    "French Southern Territories":"TF",
    "Togo":"TG",
    "Thailand":"TH",
    "Tajikistan":"TJ",
    "Tokelau":"TK",
    "Timor-Leste":"TL",
    "Turkmenistan":"TM",
    "Tunisia":"TN",
    "Tonga":"TO",
    "Turkey":"TR",
    "Trinidad and Tobago":"TT",
    "Tuvalu":"TV",
    "Taiwan":"TW",
    "Tanzania, United Republic of":"TZ",
    "Ukraine":"UA",
    "Uganda":"UG",
    "United States Minor Outlying Islands":"UM",
    "United States":"US",
    "Uruguay":"UY",
    "Uzbekistan":"UZ",
    "Holy See (Vatican City State)":"VA",
    "Saint Vincent and the Grenadines":"VC",
    "Venezuela":"VE",
    "Virgin Islands, British":"VG",
    "Virgin Islands, U.S.":"VI",
    "Vietnam":"VN",
    "Vanuatu":"VU",
    "Wallis and Futuna":"WF",
    "Samoa":"WS",
    "Yemen":"YE",
    "Mayotte":"YT",
    "South Africa":"ZA",
    "Zambia":"ZM",
    "Zimbabwe":"ZW"

                      
                }
    newcountry=countrycodes.get(country)
    return newcountry
    
  def StateCodes(state):
    statecodes={
      "Alabama":"AL",
      "Alaska":"AK",
      "Arizona":"AZ",
      "Arkansas":"AR",
      "California":"CA",
      "Colorado":"CO",
      "Connecticut":"CT",
      "Delaware":"DE",
      "District of Columbia":"DC",
      "Florida":"FL",
      "Georgia":"GA",
      "Hawaii":"HI",
      "Idaho":"ID",
      "Illinois":"IL",
      "Indiana":"IN",
      "Iowa":"IA",
      "Kansas":"KS",
      "Kentucky":"KY",
      "Louisiana":"LA",
      "Maine":"ME",
      "Maryland":"MD",
      "Massachusetts":"MA",
      "Michigan":"MI",
      "Minnesota":"MN",
      "Mississippi":"MS",
      "Missouri":"MO",
      "Montana":"MT",
      "Nebraska":"NE",
      "Nevada":"NV",
      "New Hampshire":"NH",
      "New Jersey":"NJ",
      "New Mexico":"NM",
      "New York":"NY",
      "North Carolina":"NC",
      "North Dakota":"ND",
      "Ohio":"OH",
      "Oklahoma":"OK",
      "Oregon":"OR",
      "Pennsylvania":"PA",
      "Rhode Island":"RI",
      "South Carolina":"SC",
      "South Dakota":"SD",
      "Tennessee":"TN",
      "Texas":"TX",
      "Utah":"UT",
      "Vermont":"VT",
      "Virginia":"VA",
      "Washington":"WA",
      "West Virginia":"WV",
      "Wisconsin":"WI",
      "Wyoming":"WY",
      "Guam":"GU",
      "Puerto Rico":"PR",
      "Virgin Islands":"VI",
      "Marshall Islands":"MH",
      "Alberta":"AB",
      "British Columbia":"BC",
      "Manitoba":"MB",
      "New Brunswick":"NB",
      "Newfoundland and Labrador":"NL",
      "Northwest Territories":"NT",
      "Nova Scotia":"NS",
      "Nunavut":"NU",
      "Ontario":"ON",
      "Prince Edward Island":"PE",
      "Quebec":"QC",
      "Saskatchewan":"SK",
      "Yukon":"YT"
      
      

              }
    newstate=statecodes.get(state)
    return newstate

  def ZoomIndustryCodes(industry):
    industrycodes={
      "Accounting & Accounting Services":"Business Services",
      "Advertising & Marketing":"Business Services",
      "Aerospace & Defense":"Aerospace & Defense",
      "Aggregates, Concrete & Cement":"Construction/Architecture/Engineering",
      "Agriculture":"Agriculture",
      "Airlines, Airports & Air Services":"Transportation & Logistics",
      "Amusement Parks, Arcades & Attractions":"Recreation",
      "Animals & Livestock":"Agriculture",
      "Apparel & Accessories":"Apparel & Textiles",
      "Appliances":"Consumer Goods & Services",
      "Architecture, Engineering & Design":"Construction/Architecture/Engineering",
      "Auctions":"Business Services",
      "Automobile Parts Stores":"Automotive",
      "Automobiles":"Automotive",
      "Automotive Service & Collision Repair":"Automotive",
      "Banking":"Financial Services",
      "Batteries, Power Storage Equipment & Generators":"Electronics",
      "Biotechnology":"Biotech",
      "Boats & Submarines":"Aerospace & Defense",
      "Broadcasting":"Media & Entertainment",
      "Brokerage":"Financial Services",
      "Building Materials":"Construction/Architecture/Engineering",
      "Business Services":"Business Services",
      "Cable & Satellite":"Telecommunications",
      "Call Centers & Business Centers":"Business Services",
      "Car & Truck Rental":"Automotive",
      "Chambers of Commerce":"Government - State & Local",
      "Charitable Organizations & Foundations":"Non-Profit",
      "Chemicals":"Manufacturing",
      "Chemicals, Petrochemicals, Glass & Gases":"Energy & Utilities",
      "Cities, Towns & Municipalities":"Government - State & Local",
      "Cleaning Products":"Consumer Goods & Services",
      "Colleges & Universities":"Education",
      "Commercial & Residential Construction":"Construction/Architecture/Engineering",
      "Commercial Printing":"Printing & Publishing",
      "Computer Equipment & Peripherals":"Computer Hardware/Software/Technology Manufacturer",
      "Computer Networking Equipment":"Computer Hardware/Software/Technology Manufacturer",
      "Computer Storage Equipment":"Computer Hardware/Software/Technology Manufacturer",
      "Construction":"Construction/Architecture/Engineering",
      "Consumer Electronics":"Electronics",
      "Consumer Electronics & Computers":"Electronics",
      "Consumer Goods":"Consumer Goods & Services",
      "Consumer Services":"Consumer Goods & Services",
      "Cosmetics, Beauty Supply & Personal Care Products":"Consumer Goods & Services",
      "Content & Collaboration Software":"Computer Hardware/Software/Technology Manufacturer",
      "Credit Cards & Transaction Processing":"Financial Services",
      "Crops":"Agriculture",
      "Cultural":"Media & Entertainment",
      "Custom Software & Technical Consulting":"Computer Services/Consulting",
      "Customer Relationship Management Software(CRM)":"Computer Hardware/Software/Technology Manufacturer",
      "Debt Collection":"Business Services",
      "Department Stores & Superstores":"Retail & Distribution",
      "Drug Manufacturing & Research":"Pharmaceutical",
      "Drug Stores & Pharmacies":"Retail & Distribution",
      "Education":"Education",
      "Electricity, Oil & Gas":"Energy & Utilities",
      "Electronic Components":"Electronics",
      "Electronics":"Electronics",
      "Emergency Medical Transportation & Services":"Healthcare & Medical",
      "Energy, Utilities & Waste Treatment":"Energy & Utilities",
      "Engineering Software":"Computer Hardware/Software/Technology Manufacturer",
      "Enterprise Resource Planning Software(ERP)":"Computer Hardware/Software/Technology Manufacturer",
      "Facilities Management & Commercial Cleaning":"Business Services",
      "Film/Video Production & Services":"Media & Entertainment",
      "Finance":"Financial Services",
      "Fitness & Dance Facilities":"Recreation",
      "Flowers, Gifts & Specialty":"Retail & Distribution",
      "Food & Beverages":"Food & Beverage",
      "Freight & Logistics Services":"Transportation & Logistics",
      "Funeral Homes & Funeral Related Services":"Consumer Goods & Services",
      "Furniture":"Furniture",
      "Gambling & Gaming":"Recreation",
      "Gas Stations, Convenience & Liquor Stores":"Retail & Distribution",
      "Gases":"Energy & Utilities",
      "Glass & Clay":"Manufacturing",
      "Government":"Government - Federal",
      "Grocery":"Retail & Distribution",
      "Hair Salons":"Consumer Goods & Services",
      "Health & Nutrition Products":"Consumer Goods & Services",
      "Healthcare":"Healthcare & Medical",
      "Home Improvement & Hardware":"Hardware",
      "Hospitality":"Hospitality & Travel",
      "Hospitals & Clinics":"Healthcare & Medical",
      "Household Goods":"Consumer Goods & Services",
      "Human Resources & Staffing":"Business Services",
      "Industrial Machinery & Equipment":"Manufacturing",
      "Information & Document Management":"Computer Services/Consulting",
      "Information Collection & Delivery":"Computer Services/Consulting",
      "Insurance":"Financial Services",
      "Internet Service Providers, Website Hosting & Internet-related Services":"Computer/Technology Reseller",
      "Investment Banking":"Financial Services",
      "Jewelry & Watches":"Consumer Goods & Services",
      "K-12 Schools":"Education",
      "Laundry & Dry Cleaning Services":"Consumer Goods & Services",
      "Law Firms & Legal Services":"Legal",
      "Libraries":"Non-Profit",
      "Lodging & Resorts":"Hospitality & Travel",
      "Lumber & Wood Production":"Construction/Architecture/Engineering",
      "Management Consulting":"Business Services",
      "Manufacturing":"Manufacturing",
      "Marine Shipping & Transportation":"Transportation & Logistics",
      "Media & Internet":"Media & Entertainment",
      "Medical Devices & Equipment":"Healthcare & Medical",
      "Medical Testing & Clinical Laboratories":"Healthcare & Medical",
      "Membership Organizations":"Associations",
      "Metals & Minerals":"Mining",
      "Mining":"Mining",
      "Miscellaneous Building Materials - Flooring, Cabinets, etc.":"Construction/Architecture/Engineering",
      "Motor Vehicle Dealers":"Automotive",
      "Movie Theaters":"Media & Entertainment",
      "Multimedia & Graphic Design":"Business Services",
      "Museums & Art Galleries":"Media & Entertainment",
      "Music & Music Related Services":"Media & Entertainment",
      "Network Security Hardware & Software":"Computer Hardware/Software/Technology Manufacturer",
      "Newspapers & News Services":"Printing & Publishing",
      "Office Products":"Retail & Distribution",
      "Oil & Gas Exploration & Services":"Energy & Utilities",
      "Personal Computers & Peripherals":"Computer Hardware/Software/Technology Manufacturer",
      "Pet Products":"Consumer Goods & Services",
      "Petrochemicals":"Energy & Utilities",
      "Pharmaceuticals":"Pharmaceuticals",
      "Photographic & Optical Equipment":"Computer/Technology Reseller",
      "Photography Studio":"Consumer Goods & Services",
      "Plastic, Packaging & Containers":"Manufacturing",
      "Plumbing & HVAC Equipment":"Manufacturing",
      "Power Conversion & Protection Equipment":"Electronics",
      "Public Safety":"Government - State & Local",
      "Publishing":"Printing & Publishing",
      "Pulp & Paper":"Manufacturing",
      "Radio Stations":"Media & Entertainment",
      "Rail, Bus & Taxi":"Transportation & Logistics",
      "Real Estate":"Real Estate",
      "Records, Videos & Books":"Retail & Distribution",
      "Recreation":"Recreation",
      "Religious Organizations":"Non-Profit",
      "Rental - Other - Furniture, A/V, Construction & Industrial Equipment":"Retail & Distribution",
      "Rental - Video & DVD ":"Retail & Distribution",
      "Restaurants":"Food & Beverage",
      "Retail":"Retail & Distribution",
      "Retail Software":"Computer Hardware/Software/Technology Manufacturer",
      "Search Engines & Internet Portals":"Computer Services/Consulting",
      "Security Products & Services":"Business Services",
      "Security software":"Computer Hardware/Software/Technology Manufacturer",
      "Semiconductor & Semiconductor Equipment":"Electronics",
      "Software":"Computer Hardware/Software/Technology Manufacturer",
      "Software Development & Design":"Computer Hardware/Software/Technology Manufacturer",
      "Sporting & Recreational Equipment":"Manufacturing",
      "Sporting Goods":"Retail & Distribution",
      "Sports Teams & Leagues":"Recreation",
      "Storage & System Management Software":"Computer Hardware/Software/Technology Manufacturer",
      "Telecommunication Equipment":"Telecommunications",
      "Telecommunications":"Telecommunications",
      "Telephony & Wireless":"Telecommunications",
      "Television Stations":"Media & Entertainment",
      "Test & Measurement Equipment":"Manufacturing",
      "Textiles & Apparel":"Apparel & Textiles",
      "Tires & Rubber":"Manufacturing",
      "Tobacco":"Manufacturing",
      "Toys & Games":"Manufacturing",
      "Training":"Business Services",
      "Translation & Linguistic Services":"Business Services",
      "Transportation":"Transportation & Logistics",
      "Travel Agencies & Services":"Hospitality & Travel",
      "Trucking, Moving & Storage":"Transportation & Logistics",
      "Venture Capital & Private Equity":"Financial Services",
      "Veterinary Care":"Healthcare & Medical",
      "Vitamins, Supplements & Health Stores":"Healthcare & Medical",
      "Waste Treatment, Environmental Services & Recycling":"Energy & Utilities",
      "Water & Water Treatment":"Energy & Utilities",
      "Weight & Health Management":"Healthcare & Medical",
      "Wineries & Breweries":"Food & Beverage",
      "Wire & Cable":"Manufacturing",
      "Zoos & National Parks":"Recreation"

      
      
       }
    newindustry=industrycodes.get(industry)
    return newindustry

  def ZoomEmployeeRangeCodes(employeerange):
    employeerangecodes={
      "Employees.10000plus":"10000",
      "Employees.5000to9999":"9999",
      "Employees.1000to4999":"4999",
      "Employees.500to999":"999",
      "Employees.250to499":"499",
      "Employees.100to249":"249",
      "Employees.50to99":"99",
      "Employees.20to49":"49",
      "Employees.10to19":"24",
      "Employees.5to9":"9",
      "Employees.1to4":"9"

                      }
    newemployeerange=employeerangecodes.get(employeerange)
    return newemployeerange

  def ZoomDesignationCodes(designation):
    designationcodes={
      "C-Level":"C-Level/President",
      "Director":"Director",
      "Non-Manager":"Staff (Associate/Analyst/etc.)",
      "Manager":"Manager",
      "VP-Level":"VP"

                    }
    newdesignation=designationcodes.get(designation)
    return newdesignation

  def ZoomJobFunctionCodes(jobfunction):
    jobfunctioncodes={
      "Accounting":"Accounting/Finance/Legal",
      "Advertising":"Marketing",
      "Banking":"Accounting/Finance/Legal",
      "Biometrics":"Other",
      "Biotechnical Engineering":"Other",
      "Benefits & Compensation":"Human Resources",
      "Branding":"Marketing",
      "Business Development":"Sales",
      "Change Management":"Human Resources",
      "Chemical Engineering":"Other",
      "Civil Engineering":"Other",
      "Communications":"Marketing",
      "Compliance":"Accounting/Finance/Legal",
      "Contracts":"Accounting/Finance/Legal",
      "Customer Relations":"Administrative",
      "Database Engineering & Design":"IT - Developer",
      "Dentists":"Other",
      "Diversity":"Human Resources",
      "Doctors":"Other",
      "E-Biz":"IT - General",
      "Engineering":"IT - Developer",
      "Facilities":"Operations",
      "Finance":"Accounting/Finance/Legal",
      "General Marketing":"Marketing",
      "Governmental Lawyers & Legal Professionals":"Accounting/Finance/Legal",
      "Hardware Engineering":"IT - General",
      "Health Professionals":"Other",
      "Human Resources Generalist":"Human Resources",
      "Industrial Engineering":"Other",
      "Information Technology":"IT - General",
      "Investment Banking":"Accounting/Finance/Legal",
      "Lawyers & Legal Professionals":"Accounting/Finance/Legal",
      "Logistics":"Operations",
      "Nurses":"Other",
      "Operations":"Operations",
      "Product Management":"Operations",
      "Quality Assurance":"IT - Tester/QA",
      "Quality Management":"IT - Tester/QA",
      "Recruiting":"Human Resources",
      "Sales":"Sales",
      "Software Engineering":"IT - Developer",
      "Sourcing":"Accounting/Finance/Legal",
      "Technical":"IT - General",
      "Wealth Management":"Accounting/Finance/Legal",
      "Web Development":"IT - Developer",
      "Other":"Other"


                     }
    newjobfunction=jobfunctioncodes.get(jobfunction)
    return newjobfunction
 
  def ZoomDecisionCodes(decision):
    decisioncodes={
      "Academic/ResearchC-Level/President":"Align Business & IT Goals",
      "Academic/ResearchVP":"Create IT Strategy",
      "Academic/ResearchDirector":"Create IT Strategy",
      "Academic/ResearchManager":"Other Role in IT Decision Making Process",
      "Academic/ResearchStaff (Associate/Analyst/etc.)":"Not Involved in IT Decision Making Process",
      "Accounting/Finance/LegalC-Level/President":"Authorize Purchases",
      "Accounting/Finance/LegalVP":"Authorize Purchases",
      "Accounting/Finance/LegalDirector":"Authorize Purchases",
      "Accounting/Finance/LegalManager":"Authorize Purchases",
      "Accounting/Finance/LegalStaff (Associate/Analyst/etc.)":"Authorize Purchases",
      "AdministrativeC-Level/President":"Authorize Purchases",
      "AdministrativeVP":"Authorize Purchases",
      "AdministrativeDirector":"Authorize Purchases",
      "AdministrativeManager":"Authorize Purchases",
      "AdministrativeStaff (Associate/Analyst/etc.)":"Not Involved in IT Decision Making Process",
      "ConsultantC-Level/President":"Align Business & IT Goals",
      "ConsultantVP":"Create IT Strategy",
      "ConsultantDirector":"Align Business & IT Goals",
      "ConsultantManager":"Create IT Strategy",
      "ConsultantStaff (Associate/Analyst/etc.)":"Evaluate/Specify Brands or Vendors",
      "General ManagementC-Level/President":"Authorize Purchases",
      "General ManagementVP":"Authorize Purchases",
      "General ManagementDirector":"Authorize Purchases",
      "General ManagementManager":"Authorize Purchases",
      "General ManagementStaff (Associate/Analyst/etc.)":"Not Involved in IT Decision Making Process",
      "Human ResourcesC-Level/President":"Align Business & IT Goals",
      "Human ResourcesVP":"Authorize Purchases",
      "Human ResourcesDirector":"Authorize Purchases",
      "Human ResourcesManager":"Not Involved in IT Decision Making Process",
      "Human ResourcesStaff (Associate/Analyst/etc.)":"Not Involved in IT Decision Making Process",
      "IT - DeveloperC-Level/President":"Align Business & IT Goals",
      "IT - DeveloperVP":"Authorize Purchases",
      "IT - DeveloperDirector":"Create IT Strategy",
      "IT - DeveloperManager":"Evaluate/Specify Brands or Vendors",
      "IT - DeveloperStaff (Associate/Analyst/etc.)":"Evaluate/Specify Brands or Vendors",
      "IT - GeneralC-Level/President":"Authorize Purchases",
      "IT - GeneralVP":"Authorize Purchases",
      "IT - GeneralDirector":"Authorize Purchases",
      "IT - GeneralManager":"Authorize Purchases",
      "IT - GeneralStaff (Associate/Analyst/etc.)":"Evaluate/Specify Brands or Vendors",
      "IT - Project ManagementC-Level/President":"Align Business & IT Goals",
      "IT - Project ManagementVP":"Align Business & IT Goals",
      "IT - Project ManagementDirector":"Create IT Strategy",
      "IT - Project ManagementManager":"Align Business & IT Goals",
      "IT - Project ManagementStaff (Associate/Analyst/etc.)":"Align Business & IT Goals",
      "IT - Systems/Network AdministrationC-Level/President":"Authorize Purchases",
      "IT - Systems/Network AdministrationVP":"Authorize Purchases",
      "IT - Systems/Network AdministrationDirector":"Authorize Purchases",
      "IT - Systems/Network AdministrationManager":"Create IT Strategy",
      "IT - Systems/Network AdministrationStaff (Associate/Analyst/etc.)":"Evaluate/Specify Brands or Vendors",
      "IT - Tester/QAC-Level/President":"Align Business & IT Goals",
      "IT - Tester/QAVP":"Authorize Purchases",
      "IT - Tester/QADirector":"Authorize Purchases",
      "IT - Tester/QAManager":"Authorize Purchases",
      "IT - Tester/QAStaff (Associate/Analyst/etc.)":"Evaluate/Specify Brands or Vendors",
      "MarketingC-Level/President":"Authorize Purchases",
      "MarketingVP":"Authorize Purchases",
      "MarketingDirector":"Authorize Purchases",
      "MarketingManager":"Not Involved in IT Decision Making Process",
      "MarketingStaff (Associate/Analyst/etc.)":"Not Involved in IT Decision Making Process",
      "OperationsC-Level/President":"Authorize Purchases",
      "OperationsVP":"Authorize Purchases",
      "OperationsDirector":"Authorize Purchases",
      "OperationsManager":"Authorize Purchases",
      "OperationsStaff (Associate/Analyst/etc.)":"Other Role in IT Decision Making Process",
      "OtherC-Level/President":"Authorize Purchases",
      "OtherVP":"Authorize Purchases",
      "OtherDirector":"Authorize Purchases",
      "OtherManager":"Authorize Purchases",
      "OtherStaff (Associate/Analyst/etc.)":"Not Involved in IT Decision Making Process",
      "SalesC-Level/President":"Align Business & IT Goals",
      "SalesVP":"Align Business & IT Goals",
      "SalesDirector":"Other Role in IT Decision Making Process",
      "SalesManager":"Not Involved in IT Decision Making Process",
      "SalesStaff (Associate/Analyst/etc.)":"Not Involved in IT Decision Making Process"

                  }
    newdecision=decisioncodes.get(decision)
    return newdecision
  